spring:
  application:
    name: idea-eureka

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.198.138:8761/eureka/,http://192.168.198.138:8861/eureka/,http://192.168.198.138:8961/eureka/
