spring:
  application:
    name: idea-service-upload

server:
  port: 8505

fastdfs.base.url: http://192.168.198.130:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.198.130:22122