stages:
  - build
  - push
  - run
  - clean

build:
  stage: build
  script:
    - /usr/local/maven/apache-maven-3.5.3/bin/mvn clean package
    - cp target/idea-admin-1.0.0-SNAPSHOT.jar docker/
    - cd docker
    - docker build -t 192.168.198.130:5000/idea-admin .

push:
  stage: push
  script:
    - docker push 192.168.198.130:5000/idea-admin

run:
  stage: run
  script:
    - cd docker
    - docker-compose up -d

clean:
  stage: clean
  script:
    - docker rmi $(docker images -q -f dangling=true)